# Generated by Django 3.2.7 on 2021-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepthought',
            name='title_text',
            field=models.CharField(default='', max_length=200, verbose_name='title_text'),
        ),
        migrations.AlterField(
            model_name='deepthought',
            name='thought_text',
            field=models.CharField(max_length=200, verbose_name='thought_text'),
        ),
    ]
